version: 2

.job_configuration: &job_configuration
  docker:
    - image: gableroux/dotnet-mono-monogame:latest
  working_directory: ~/repo
  steps:
    - checkout
    - ./build.sh
    - store_artifacts:
        path: ~/repo/artifacts/

environment:
  PROJECT_NAME: example_project_name
  MONOGAME_CONTENT_VERSION: 3.7.0.4

jobs:
  windows:
    <<: *job_configuration
    environment:
      BUILD_PLATFORM: 'win-x64'
  linux:
    <<: *job_configuration
    environment:
      BUILD_PLATFORM: 'linux-x64'
  macos:
    <<: *job_configuration
    environment:
      BUILD_PLATFORM: 'osx-x64'

workflows:
  version: 2
  workflow:
    jobs:
      - windows
      - linux
      - macos

