version: 2

.job_configuration: &job_configuration
  docker:
    - image: gableroux/dotnet-mono-monogame
  working_directory: ~/repo
  steps:
    - checkout
    - run: dotnet restore
    - run: chmod +x /root/.nuget/packages/monogame.content.builder/3.7.0.4/build/MGCB/build/ffprobe
    - run: chmod +x /root/.nuget/packages/monogame.content.builder/3.7.0.4/build/MGCB/build/ffmpeg
    - run: dotnet build PROJECT_NAME.csproj --configuration $BUILDCONFIGURATION
    - run: dotnet publish -r $BUILDPLATFORM --configuration $BUILDCONFIGURATION /p:TrimUnusedDependencies=true
    - store_artifacts:
        path: ~/repo/bin/release/netcoreapp2.2/$BUILDPLATFORM/publish

jobs:
  windows:
    <<: *job_configuration
    environment:
      BUILDCONFIGURATION: 'release'
      BUILDPLATFORM: 'win-x64'
  linux:
    <<: *job_configuration
    environment:
      BUILDCONFIGURATION: 'release'
      BUILDPLATFORM: 'linux-x64'
  macos:
    <<: *job_configuration
    environment:
      BUILDCONFIGURATION: 'release'
      BUILDPLATFORM: 'osx-x64'

workflows:
  version: 2
  workflow:
    jobs:
      - windows
      - linux
      - macos